# Generated by Django 2.2.16 on 2020-10-08 23:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientProductProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='¿Proveedor Activo?')),
                ('image', models.ImageField(upload_to='products_providers', verbose_name='Imagen del proveedor')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del proveedor')),
                ('cc_nit', models.CharField(max_length=40, unique=True, verbose_name='C.C o NIT')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Telefono (fijo)')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Telefono (celular)')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Correo electrónico')),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor del ingrediente',
                'verbose_name_plural': 'Proveedores de los ingredientes',
            },
        ),
        migrations.CreateModel(
            name='IngredientProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de la categoría')),
                ('active', models.BooleanField(default=True, verbose_name='¿Categoría Activa?')),
                ('image', models.ImageField(upload_to='products_categories', verbose_name='Imagen de la categoría')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la categoría')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.IngredientProductCategory', verbose_name='Categoría de producto padre')),
            ],
            options={
                'verbose_name': 'Categoría del producto ingrediente',
                'verbose_name_plural': 'Categorías de productos ingredientes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IngredientProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='¿Ingrediente Activo?')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen del producto')),
                ('barcode', models.CharField(blank=True, max_length=60, verbose_name='Código de barras')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(max_length=480, verbose_name='Descripción')),
                ('tax', models.FloatField(default=0.0, verbose_name='Impuesto (%)')),
                ('unit_price', models.BigIntegerField(verbose_name='Precio unitario')),
                ('sale_price', models.BigIntegerField(blank=True, verbose_name='Precio de venta')),
                ('stock', models.SmallIntegerField(default=1, verbose_name='Cantidad en inventario')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden del ingrediente')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.IngredientProductCategory', verbose_name='Categoría a la que pertenece')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.IngredientProductProvider', verbose_name='Proveedor del Ingrediente')),
            ],
            options={
                'verbose_name': 'Producto ingrediente',
                'verbose_name_plural': 'Productos ingredientes',
                'ordering': ['order'],
            },
        ),
    ]
