# Generated by Django 2.2.16 on 2020-10-09 00:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientproduct',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='ingredientproduct',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='ingredientproduct',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='ingredientproduct',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='ingredientproduct',
            name='unit',
            field=models.CharField(choices=[('U', 'Unidad(es)'), ('P', 'Porción(es)')], default=1, max_length=20, verbose_name='Cantidad en inventario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientproduct',
            name='description',
            field=models.TextField(blank=True, max_length=480, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ingredientproductcategory',
            name='image',
            field=models.ImageField(upload_to='ingredient_products_categories', verbose_name='Imagen de la categoría'),
        ),
        migrations.AlterField(
            model_name='ingredientproductcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.IngredientProductCategory', verbose_name='Categoría padre'),
        ),
    ]
