# Generated by Django 2.2.16 on 2020-10-09 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20201008_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Precio Total')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.Invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductStore', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de la venta',
                'verbose_name_plural': 'Detalles de la venta',
                'unique_together': {('id', 'invoice')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, through='pdv.InvoiceDetail', to='store.ProductStore'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor(a)'),
        ),
    ]
