# Generated by Django 2.2.16 on 2020-10-09 00:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de la categoría')),
                ('active', models.BooleanField(default=True, verbose_name='¿Categoría Activa?')),
                ('image', models.ImageField(upload_to='products_categories', verbose_name='Imagen de la categoría')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la categoría')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.ProductCategory', verbose_name='Categoría de producto padre')),
            ],
            options={
                'verbose_name': 'Categoría del producto',
                'verbose_name_plural': 'Categorías de productos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='¿Producto Activo?')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen del producto')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(max_length=480, verbose_name='Descripción')),
                ('barcode', models.CharField(blank=True, max_length=60, verbose_name='Código de barras')),
                ('price', models.BigIntegerField(verbose_name='Precio')),
                ('discount', models.FloatField(default=0.0, verbose_name='Descuento (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden del producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductCategory', verbose_name='Categoría a la que pertenece')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['order'],
            },
        ),
    ]
