# Generated by Django 2.2.16 on 2020-10-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201008_2014'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientOfProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ingredient_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_of_products', to='inventory.IngredientProduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_of_products', to='store.ProductStore')),
            ],
        ),
        migrations.AddField(
            model_name='productstore',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='store.IngredientOfProductStore', to='inventory.IngredientProduct', verbose_name='Ingredientes'),
        ),
    ]
