# Generated by Django 2.2.16 on 2020-10-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201008_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientofproductstore',
            options={'verbose_name': 'Ingrediente del producto', 'verbose_name_plural': 'Ingredientes de los Productos'},
        ),
        migrations.AlterField(
            model_name='ingredientofproductstore',
            name='ingredient_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_of_products', to='inventory.IngredientProduct', verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredientofproductstore',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
